chg: Cache Bazel build results between builds

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -11,20 +11,37 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
+        folder:
+          - "."
+
     steps:
       - name: Checkout repository and submodules
-        uses: actions/checkout@v2
-        with:
-          submodules: recursive
-      - name: Find untagged tests
+        uses: actions/checkout@v3
+
+      # We deliberately do not load Bazel cache on nightly builds to force full rebuilds
+
+      - name: Check source code
+        env:
+          # Bazelisk will download bazel to here, ensure it is cached between runs.
+          XDG_CACHE_HOME: ~/.cache/bazel-repo
+        working-directory: ${{ matrix.folder }}
         run: |
           UNTAGGED_TESTS=$(bazel query 'tests(//...) except attr(tags, L0, tests(//...)) except attr(tags, L1, tests(//...)) except attr(tags, L2, tests(//...)) except attr(tags, L3, tests(//...)) except attr(tags, Nightly, tests(//...)) except attr(tags, manual, tests(//...))')
           if [ -n "${UNTAGGED_TESTS}" ]; then
             echo "ERROR: Following Bazel tests are untagged: ${UNTAGGED_TESTS}" 1>&2
             exit 1
           fi
-        if: runner.os == 'Linux'
-      - name: Build
-        run: bazel build --config=github //...
-      - name: Test
-        run: bazel test --config=github //...
+
+          BUILD_FILES=$(find . -name "BUILD")
+          if [ -n "${BUILD_FILES}" ]; then
+            echo "ERROR: Following BUILD files are named BUILD not BUILD.bazel: ${BUILD_FILES}" 1>&2
+            exit 1
+          fi
+        shell: bash
+
+      - name: bazel test //...
+        env:
+          # Bazelisk will download bazel to here, ensure it is cached between runs.
+          XDG_CACHE_HOME: ~/.cache/bazel-repo
+        working-directory: ${{ matrix.folder }}
+        run: bazel --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
